LAB_CHOICES = (
    "DEI/A | 016 DEI/A",
    "DEI/A | 018 DEI/A",
    "DEI/A | 115 DEI/A",
    "DEI/A | 206 DEI/A",
    "DEI/A | 209 DEI/A",
    "DEI/A | 219 DEI/A",
    "DEI/A | 224 DEI/A",
    "DEI/A | 230 DEI/A",
    "DEI/A | 231 DEI/A",
    "DEI/A | 301 DEI/A",
    "DEI/A | 305b DEI/A (ex compat. elettromagn. e misure)",
    "DEI/A | 310 DEI/A",
    "DEI/A | 326 DEI/A",
    "DEI/A | 329a DEI/A",
    "DEI/A | 330 DEI/A",
    "DEI/A | BioDevices",
    "DEI/A | Elettronica di potenza",
    "DEI/A | ICARUS",
    "DEI/A | LED",
    "DEI/A | LTTM",
    "DEI/A | Microelettronica",
    "DEI/A | MOSLAB",
    "DEI/A | NAVLAB",
    "DEI/A | Optoelettronica",
    "DEI/A | Prove affidabilità - Microelettronica",
    "DEI/A | PVLab",
    "DEI/A | RREACT",
    "DEI/A | UV",
    "DEI/D | ACME",
    "DEI/D | Fotonica e Campi Elettromagnetici",
    "DEI/D | Reti di Telecomunicazioni",
    "DEI/D | Sistemi di Controllo",
    "DEI/D | SPARCS",
    "DEI/G | 125 DEI/G",
    "DEI/G | 126 DEI/G",
    "DEI/G | 127 DEI/G",
    "DEI/G | 128 DEI/G",
    "DEI/G | 129 DEI/G",
    "DEI/G | 303 DEI/G",
    "DEI/G | 305 DEI/G",
    "DEI/G | 417 DEI/G",
    "DEI/G | 418 DEI/G",
    "DEI/G | 418B/MICRO",
    "DEI/G | 419 DEI/G",
    "DEI/G | Compatibilità Elettromagnetica",
    "DEI/G | Misure Elettroniche",
    "DEI/G | Progettazione Elettronica",
    "DEI/G | SIGNET",
    "DEI/O | Autonomous Robotics Laboratory",
    "DEI/O | IAS-Lab",
    "DEI/O | Robot Vision Lab",
    "DEI/O | SSL Lab",
    "DEI/P | Informatica Musicale 1",
    "DEI/S | 102 DEI/S",
    "DEI/S | 103 DEI/S",
    "DEI/S | Bioingegneria del Movimento",
    "DEI/S | Centro Sonologia Computazionale - Produzione Musicale",
    "DEI/S | Centro Sonologia Computazionale - Restauro Audio",
    "DEI/S | Informatica Musicale ",
)